var b=Object.defineProperty;var w=(t,e,s)=>e in t?b(t,e,{enumerable:!0,configurable:!0,writable:!0,value:s}):t[e]=s;var g=(t,e,s)=>(w(t,typeof e!="symbol"?e+"":e,s),s);import{a as f,S as L,i as d}from"./assets/vendor-b11e2a50.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(r){if(r.ep)return;r.ep=!0;const a=s(r);fetch(r.href,a)}})();f.defaults.baseURL="https://pixabay.com/api/";const P="44402631-bf7d189f653a3e22d2fd50e44";class v{constructor(){this.page=1,this.searchQuery="",this.perPage=15}async getImages(){const e={key:P,q:this.searchQuery,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:this.perPage,page:this.page},{data:s}=await f.get("",{params:e});return this.incrementPage(),s}resetPage(){this.page=1}incrementPage(){this.page+=1}}const h={imageWrapper:document.querySelector(".js-imageWrapper")},x=new L(".img-card a");function S({webformatURL:t,largeImageURL:e,tags:s,likes:n,views:r,comments:a,downloads:l}){return`<div class="img-card">
            <a href="${e}"><img src="${t}" alt="${s}"></a> 
            <div class="text-wrapper">
            <p class="text">Likes<span class="wrapper">${n}</span></p>
            <p class="text">Views<span class="wrapper">${r}</span></p>
            <p class="text">Comments<span class="wrapper">${a}</span></p>
            <p class="text">Downloads<span class="wrapper">${l}</span></p></div>
            </div>`}function I(t){h.imageWrapper.insertAdjacentHTML("beforeend",t),x.refresh()}function m(){h.imageWrapper.innerHTML=""}const i=class i{constructor({selector:e,isHidden:s=!1}){this.button=this.getButton(e),s&&this.hide()}getButton(e){return document.querySelector(e)}hide(){this.button.classList.add(i.classes.hidden)}show(){this.button.classList.remove(i.classes.hidden)}disable(){this.button.disabled=!0,this.button.textContent="",this.button.classList.add(i.classes.loader)}enable(){this.button.disabled=!1,this.button.textContent="Load more",this.button.classList.remove(i.classes.loader)}};g(i,"classes",{hidden:"hidden",loader:"loader"});let p=i;function $(){const{height:t}=h.imageWrapper.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const C={form:document.querySelector(".js-form")},c=new v,o=new p({selector:".loadMore",isHidden:!0});C.form.addEventListener("submit",E);o.button.addEventListener("click",t=>y(t));function E(t){t.preventDefault();const e=t.currentTarget,s=e.elements.image.value.trim();if(s==="")return d.warning({position:"topRight",title:"Caution",message:"You forgot important data"});c.searchQuery=s,c.resetPage(),o.show(),m(),y().finally(()=>{e.reset()})}async function y(t){o.disable();try{const e=await q();e&&I(e),t&&t.target===o.button&&$()}catch{u()}o.enable()}async function q(){try{const{hits:t,totalHits:e}=await c.getImages();return t.length===0?u():(t.length<c.perPage||c.page>Math.ceil(e/c.perPage))&&(o.hide(),d.warning({position:"topRight",title:"Caution",message:"We are sorry, but you have reached the end of search results"})),t.reduce((s,n)=>s+S(n),"")}catch{u()}}function u(){o.hide(),d.error({position:"topRight",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),m()}
//# sourceMappingURL=commonHelpers.js.map
