import{S as p,i as c}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const d="https://pixabay.com/api/",u="44402631-bf7d189f653a3e22d2fd50e44",f="photo",m="horizontal",g="true";function h(o){return fetch(`${d}?key=${u}&q=${o}&image_type=${f}&orientation=${m}&safesearch=${g}`).then(t=>t.json())}const y={getImages:h},a={imageWrapper:document.querySelector(".js-imageWrapper"),loadMore:document.querySelector(".loadMore")};function L({webformatURL:o,largeImageURL:t,tags:n,likes:s,views:e,comments:r,downloads:i}){return`<div class="img-card">
            <a href="${t}"><img src="${o}" alt="${n}"></a> 
            <div class="text-wrapper">
            <p class="text">Likes<span class="wrapper">${s}</span></p>
            <p class="text">Views<span class="wrapper">${e}</span></p>
            <p class="text">Comments<span class="wrapper">${r}</span></p>
            <p class="text">Downloads<span class="wrapper">${i}</span></p></div>
            </div>`}function $(o){a.imageWrapper.insertAdjacentHTML("beforeend",o),new p(".img-card a").refresh()}function M(){a.imageWrapper.innerHTML=""}function v(){a.loadMore.textContent="",a.loadMore.classList.remove("hidden"),a.loadMore.classList.add("loader")}function w(){a.loadMore.classList.add("hidden"),a.loadMore.classList.remove("loader")}const l={form:document.querySelector(".js-form")};l.form.addEventListener("submit",b);function b(o){o.preventDefault();const t=o.currentTarget,n=t.elements.image.value.trim();if(n==="")return c.warning({title:"Caution",message:"You forgot important data"});M(),v(),y.getImages(n).then(({hits:s})=>(s.length===0&&c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),s.reduce((e,r)=>e+L(r),""))).then($).catch(x).finally(()=>{t.reset(),w()})}function x(){l.imageWrapper.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
